# Sets user-defined palette
palette = "catppuccin_mocha"
 
# $all is shorthand for $username$hostname$localip$shlvl$singularity$kubernetes$directory$vcsh$fossil_branch
#$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$pijul_channel$docker_context$package
#$bun$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$golang$gradle$haskell$haxe$helm$java
#$julia$kotlin$lua$nim$nodejs$ocaml$opa$perl$php$pulumi$purescript$python$raku$rlang$red$ruby$rust$scala
#$swift$terraform$vlang$vagrant$zig$buf$guix_shell$nix_shell$conda$meson$spack$memory_usage$aws$gcloud
#$openstack$azure$env_var$crystal$custom$sudo$cmd_duration$line_break$jobs$battery$time$status$container
#$os$shell$character
 
"$schema" = https://starship.rs/config-schema.json
 
format = """
$shell\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$container\
$dotnet\
$golang
$java\
$kotlin\
$gradle\
$lua\
$nodejs\
$perl\
$php\
$python\
$ruby\
$rust\
$scala\
$character"""
 
right_format = """
$docker_context\
$kubernetes\
$helm\
$azure\
$terraform\
$time"""
 
[fill]
symbol = ''
style = 'base dimmed'
 
[shell]
format = "[$indicator]($style) "
bash_indicator = ""
fish_indicator = "🐟"
zsh_indicator = "🚀"
powershell_indicator = ""
ion_indicator = "ion"
elvish_indicator = "esh"
tcsh_indicator = "tsh"
nu_indicator = "nu"
xonsh_indicator = "xsh"
cmd_indicator = ""
unknown_indicator = ""
style = "sky bold"
disabled = false
 
[username]
format = '\[[$user]($style)\][](peach)'
style_root = "rosewater bold"
style_user = "rosewater"
show_always = false
disabled = false
 
[hostname]
ssh_only = true
ssh_symbol = "☁️ "
trim_at = "."
format = '\[[$ssh_symbol($hostname)]($style)\] [ ](teal)'
style = "pink"
disabled = false
 
[directory]
style = "lavender bold"
truncation_length = 4
read_only_style = "lavender dimmed"
truncation_symbol = ".../"
 
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
 
[character]
success_symbol = "[❯](maroon)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"
 
[git_branch]
format = "[$branch]($style)"
style = "pink"
 
[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "rosewater"
 
[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "sapphire"
stashed = "≡"
 
[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
 
[container]
format = '[$symbol]($style) '
symbol = "⬢"
style = "maroon dimmed"
disabled = false
 
[dotnet]
format = "[$symbol(🎯 $tfm )]($style)"
version_format = "v${raw}"
symbol = " "
style = "blue bold"
heuristic = true
disabled = false
detect_extensions = [
    "csproj",
    "fsproj",
    "xproj",
]
detect_files = [
    "global.json",
    "project.json",
    "Directory.Build.props",
    "Directory.Build.targets",
    "Packages.props",
]
detect_folders = []
 
[golang]
format = "[$symbol]($style)"
version_format = "v${raw}"
symbol = " "
style = "sapphire"
disabled = false
detect_extensions = ["go"]
detect_files = [
    "go.mod",
    "go.sum",
    "go.work",
    "glide.yaml",
    "Gopkg.yml",
    "Gopkg.lock",
    ".go-version",
]
detect_folders = ["Godeps"]
 
[java]
disabled = false
format = "[$symbol]($style)"
version_format = "v${raw}"
style = "peach"
symbol = " "
detect_extensions = [
    "java",
    "class",
    "jar",
    "gradle",
    "clj",
    "cljc",
]
detect_files = [
    "pom.xml",
    "build.gradle.kts",
    "build.sbt",
    ".java-version",
    "deps.edn",
    "project.clj",
    "build.boot",
    ".sdkmanrc",
]
detect_folders = []
 
[kotlin]
format = "[$symbol]($style)"
version_format = "v${raw}"
symbol = "🅺 "
style = "mauve"
kotlin_binary = "kotlin"
disabled = false
detect_extensions = [
    "kt",
    "kts",
]
detect_files = []
detect_folders = []
 
[gradle]
format = "[$symbol]($style)"
version_format = "v${raw}"
symbol = "🅶 "
style = "teal"
disabled = false
recursive = false
detect_extensions = [
    "gradle",
    "gradle.kts",
]
detect_files = []
detect_folders = ["gradle"]
 
[lua]
format = "[$symbol]($style)"
symbol = " "
style = "yellow"
lua_binary = "lua"
detect_extensions = ["lua"]
detect_files = [".lua-version"]
detect_folders = ["lua"]
 
[nodejs]
format = "[$symbol]($style)"
symbol = " "
style = "green"
not_capable_style = "bold red"
detect_extensions = [
    "js",
    "mjs",
    "cjs",
    "ts",
    "mts",
    "cts",
]
detect_files = [
    "package.json",
    ".node-version",
    ".nvmrc",
]
detect_folders = ["node_modules"]
 
[perl]
format = "[$symbol]($style)"
version_format = "v${raw}"
symbol = "🐪 "
style = "rosewater dimmed"
disabled = false
detect_extensions = [
    "pl",
    "pm",
    "pod",
]
detect_files = [
    "Makefile.PL",
    "Build.PL",
    "cpanfile",
    "cpanfile.snapshot",
    "META.json",
    "META.yml",
    ".perl-version",
]
detect_folders = []
 
[php]
format = "[$symbol]($style)"
version_format = "v${raw}"
symbol = "🐘 "
style = "subtext0"
disabled = false
detect_extensions = ["php"]
detect_files = [
    "composer.json",
    ".php-version",
]
detect_folders = []
 
[python]
format = "[$symbol(blue)$virtualenv]($style) "
style = "yellow"
pyenv_prefix = "pyenv "
python_binary = [
    "python",
    "python3",
    "python2",
]
symbol = " "
disabled = false
detect_extensions = ["py"]
detect_files = [
    "requirements.txt",
    ".python-version",
    "pyproject.toml",
    "Pipfile",
    "tox.ini",
    "setup.py",
    "__init__.py",
]
detect_folders = []
 
[ruby]
format = "[$symbol]($style)"
version_format = "v${raw}"
symbol = "💎 "
style = "red"
disabled = false
detect_extensions = ["rb"]
detect_files = [
    "Gemfile",
    ".ruby-version",
]
detect_folders = []
detect_variables = [
    "RUBY_VERSION",
    "RBENV_VERSION",
]
 
[rust]
format = "[$symbol]($style)"
version_format = "v${raw}"
symbol = "🦀 "
style = "red"
disabled = false
detect_extensions = ["rs"]
detect_files = ["Cargo.toml"]
detect_folders = []
 
[scala]
format = "[$symbol]($style)"
version_format = "v${raw}"
disabled = false
style = "bold"
symbol = " "
detect_extensions = [
    "sbt",
    "scala",
]
detect_files = [
    ".scalaenv",
    ".sbtenv",
    "build.sbt",
]
detect_folders = [".metals"]
 
[time]
format = "[$time ]($style) "
time_format = "%R"
style = "rosewater"
use_12hr = true
disabled = false
utc_time_offset = "-4"
#time_range = "17-6"
 
[docker_context]
symbol = " "
style = "blue"
format = "[$symbol$context]($style) "
only_with_files = true
disabled = false
detect_extensions = []
detect_files = [
    "docker-compose.yml",
    "docker-compose.yaml",
    "Dockerfile",
]
detect_folders = []
 
[kubernetes]
symbol = "☸ "
format = '[$symbol$context( \($namespace\))]($style) in '
style = "sapphire"
disabled = false
detect_extensions = []
detect_files = []
detect_folders = []
 
[kubernetes.context_aliases]
 
[kubernetes.user_aliases]
 
[helm]
format = "via [$symbol($version )]($style)"
version_format = "v${raw}"
symbol = "⎈ "
style = "text"
disabled = false
detect_extensions = []
detect_files = [
    "helmfile.yaml",
    "Chart.yaml",
]
detect_folders = []
 
[azure]
format = "[$symbol($subscription)]($style) "
symbol = " "
style = "sky"
disabled = false
 
[terraform]
format = "via [$symbol$workspace]($style) "
version_format = "v${raw}"
symbol = "💠 "
style = "mauve"
disabled = false
detect_extensions = [
    "tf",
    "tfplan",
    "tfstate",
]
detect_files = []
detect_folders = [".terraform"]
 
[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
 
[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
 
[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
 
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"